version = "MatteFormer-Composition1k"
#dist = true
dist=false

[model]
trimap_channel = 3
mask_channel = 1
batch_size = 10
imagenet_pretrain = true
imagenet_pretrain_path = "/home/ljh/SLL/data/sll/MattingCode/ContextMatte/pretrained/swin_tiny_patch4_window7_224.pth"
self_refine_width1 = 30
self_refine_width2 = 15

[train]
total_step = 200000

warmup_step = 10000

val_step = 5000

clip_grad = true
G_lr = 1e-3
rec_weight = 1.0
comp_weight = 1.0
lap_weight = 1.0


[data]

#train_fg ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/fg/'
#train_alpha ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/alpha/'
#train_bg = "/home/Storage/sll/MattingCode/DataSet/train2014/"
#test_merged ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/composited_images/'
#test_alpha ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/val_alpha_copy/'
#test_trimap ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/val_trimap_copy/'
#test_fggt='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/val_trimap_copy/'

#train_fg ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Black/Training/fg/'
#train_alpha ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/alpha/'
#train_bg = "/home/Storage/sll/MattingCode/DataSet/train2014/"
#test_merged ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Low_val/composition/'
#test_alpha ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Low_val/alpha/'
#test_trimap ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Low_val/trimap/'
#test_fggt ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Low_val/fggt/'


#test_merged ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Black/Training/val_black_composition/'
#test_alpha ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/val_alpha_copy/'
#test_trimap ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Train/val_trimap_copy/'
#test_fggt ='/home/Storage/sll/MattingCode/DataSet/Transparent-460/Black/Training/val_copy/'
#train_fg ='/home/sll/data/sll/MattingCode/DataSet/Transparent-460/Black/train/low_fg/'
#train_alpha ='/home/sll/data/sll/MattingCode/DataSet/Transparent-460/Train/low_alpha/'
#train_bg = "/home/sll/data/sll/MattingCode/DataSet/train2014"
#test_merged ='/home/sll/data/sll/MattingCode/DataSet/Transparent-460/Black/train/low_merged/'
#test_alpha ='/home/sll/data/sll/MattingCode/DataSet/Transparent-460/Train/low_alpha_copy/'
#test_trimap ='/home/sll/data/sll/MattingCode/DataSet/Transparent-460/Train/low_trimap_copy/'
#test_fggt='/home/sll/data/sll/MattingCode/DataSet/Transparent-460/Black/train/low_val_black_copy/'

#train_fg ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Adobe-licensed_images/fg'
#train_alpha ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Adobe-licensed_images/alpha'
#train_bg = "/home/sll/data/sll/MattingCode/DataSet/train2014"
#test_merged ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/low_merged/'
#test_alpha ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/low_alpha_copy/'
#test_trimap ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/low_trimap_copy/'
#test_fggt='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/low_fg_copy/'
#test_merged ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/composition_bai/'
#test_alpha ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/alpha_copy/'
#test_trimap ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/trimap_copy/'
#test_fggt='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other/alpha_copy/'

train_fg ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Adobe-licensed_images/fg'
train_alpha ='/home/sll/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Adobe-licensed_images/alpha'
train_bg = "/home/sll/data/sll/MattingCode/DataSet/train2014"
test_merged ='/home/ljh/SLL/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other2/low_merged/'
test_alpha ='/home/ljh/SLL/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other2/low_alpha_t_copy/'
test_trimap ='/home/ljh/SLL/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other2/low_trimap_t_copy/'
test_fggt='/home/ljh/SLL/data/sll/MattingCode/ContextMatte/PATH/Adobe_Deep_Matting_Dataset/Combined_Dataset/Training_set/Other2/low_fg_t_copy/'

workers = 4

crop_size = 512
cutmask_prob = 0.25
augmentation = true
random_interp = true
real_world_aug = false

[log]
experiment_root = "experiments"

logging_path = "logs/stdout"
logging_step =  10
logging_level = "INFO"

checkpoint_path = "checkpoints"
checkpoint_step = 5000